### ISSUE TITLE
Automate docker build & push

### ISSUE THREAD

**Issue by amenophis** [makasim/docker-nginx-php-fpm#10]
Hi @makasim,
What do you think about automating the build / push on merge ?
If you are OK with this, I can prepare a PR about that.
And you can configure 2 secrets on the repository for DOCKER_USER and DOCKER_PASSWORD variables used in the script.

Thanks :pray:

**Comment by makasim** [comment]
That would be great!

**Comment by amenophis** [comment]
OK, can you configure the 2 secrets  DOCKERHUB_USERNAME and DOCKERHUB_TOKEN
The token should be a personal access token created from your docker account (https://github.com/docker/login-action?tab=readme-ov-file#docker-hub)

I'm working on the PR in parallel

Thanks

**Comment by makasim** [comment]
sure!

**Comment by makasim** [comment]
done <img width="820" alt="Screenshot 2024-04-08 at 13 45 02" src="https://github.com/makasim/docker-nginx-php-fpm/assets/143206/3f0468b1-c803-48eb-8cd1-56d6c2a85480">

**Comment by amenophis** [comment]
The PR is here https://github.com/makasim/docker-nginx-php-fpm/pull/11 :) 

Don't know if you have something to configure other than the 2 secrets to ake it run ?

I tested it locally with a personnal docker repo, and everything seems to be ok !

**Comment by makasim** [comment]
we'll see https://github.com/makasim/docker-nginx-php-fpm/actions/runs/8600671776

**Comment by makasim** [comment]
failed, btw you can add automation for the latest php version. That's ok for me.

**Comment by amenophis** [comment]
The build is green :smile: 
I will add latest later

**Comment by makasim** [comment]
Thank you for your effort! I appreciate it.
